### ISSUE TITLE
Interstitial?

### ISSUE THREAD

**Issue by adarsh** [gabebw/hotline-webring#18]
For branding purposes, what if, in the middle of redirecting, you sat on an interstitial page with a random Drake GIF from Giphy?

**Comment by edwardloveall** [comment]
I'll be honest, I am not all that keen on the Drake branding. Name is fine, Drake less so

**Comment by gabebw** [comment]
Yeah, Drake is _pretty_ sexist.

I think an interstitial would annoy people -- I'd like to keep the barriers to entry and usage very low.

**Comment by adarsh** [comment]
Glad I don't watch the news.

Did you know Trump is super racist?

On Wednesday, December 9, 2015, Gabe Berke-Williams <
notifications@github.com> wrote:

> Closed #18 <https://github.com/gabebw/hotline-webring/issues/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabebw/hotline-webring/issues/18#event-487730350>.
>


-- 


-- 
@adarshp <http://www.twitter.com/adarshp>
313.454.1515 (mobile)
See when I am free: http://bit.ly/adarshcal
