### ISSUE TITLE
Many Webrings

### ISSUE THREAD

**Issue by adarsh** [gabebw/hotline-webring#19]
What about nesting the resources and allowing people to create their own separate rings, rather than one massive one?

e.g. `http://hotlinewebring.club/ruby/adarsh/next` and `http://hotlinewebring.club/fans_of_grumpy_cat/gabebw/next` would create separate rings, which would keep affiliated sites actually linked together.

**Comment by edwardloveall** [comment]
Interesting idea, but I don't think there's really a want to justify this feature at the moment. Plus, it's open source so the scope of the webring could be more limited to the domain. So, this is the Hotline Webring, vs other webrings out there that use this codebase.

**Comment by gabebw** [comment]
I agree with @edwardloveall -- I think we don't have enough people to justify more than one webring.

Plus I kind of like having everyone in One [Big Webring](https://www.youtube.com/watch?v=zsl5D03rfzk).
