### ISSUE TITLE
Allow blacklisting certain URLs

### ISSUE THREAD

**Issue by gabebw** [gabebw/hotline-webring#206]
These URLs can't join the webring even if they try.

Idea: use a table named `blacklisted_referrers` with the following schema:

* `prefix` as `string`
* Rails standard timestamps

I suggest we check if an incoming URL *starts with* any of the blacklisted referrers. That way if we blacklist `evil.com`, we also blacklist `evil.com/~hello`, `evil.com/about`, but not `good.evil.com`.

I think we should not block a blacklisted URL's subdomains (at least for now) since usually subdomains are totally different sites (e.g. `something.tumblr.com` vs `another-thing.tumblr.com`).

There are some edge cases like `http://freepages.rootsweb.com/`, which uses directories, not subdomains, to indicate different sites: `http://freepages.rootsweb.com/~good` is totally different from `http://freepages.rootsweb.com/~bad`. However, this scheme also handles that because we can block `http://freepages.rootsweb.com/~bad`, which wouldn't touch `http://freepages.rootsweb.com/~good`.

**Comment by edwardloveall** [comment]
This is great and exactly what I was thinking. A V2 of this could also add:

* Redirect the blacklisted site to a message telling them why
* A Code of conduct to explain what we do and do not accept

**Comment by edwardloveall** [comment]
Interesting. I think that might make it seam like hotline webring is broken, no? An alternative is we show the message of why it's blocked and then link to our site.

Or maybe it just looks like their site is bad.

**Comment by gabebw** [comment]
Alternatively, we can add a `skip` boolean (or timestamp: https://github.com/calebthompson/time_for_a_boolean) field to the existing `redirections` table, and if `skip == false`, display the Code of Conduct when someone clicks that link.

I think I'd prefer a separate table, because:

1) It's clearer what's going on
2) It means we don't keep around a `Redirection` that we don't like - all `Redirection`s are "good links"
3) We can store more information in a separate table. It's more flexible than adding fields to an existing table.
