### ISSUE TITLE
Testing a webring locally stores localhost

### ISSUE THREAD

**Issue by gabebw** [gabebw/hotline-webring#21]
https://twitter.com/alexeyzab/status/676889281437282304

> Think I might have messed up the webring. Somehow it points to localhost instead of my site. :(

Idea: if a request comes in with `localhost` as the referrer, we _don't_ store them in the webring, but do provide a redirect (to anything, let's say `Redirect.first`) so people know it works.

**Comment by gabebw** [comment]
Even better: Make a custom landing page for hotlinewebring.club that tells people that since they're testing locally, they're not in the webring yet, but it'll get added once it's live. And encourage them to only click the link on production, not on staging.

**Comment by edwardloveall** [comment]
Another idea: we have a tool that scans someone's webpage to check for:

* Links that link to next and previous
* A unique slug in those links

**Comment by gabebw** [comment]
Yeah, that sounds like a good addition on top of the landing page. How do we contact them if they mess it up?

**Comment by edwardloveall** [comment]
Now that I thought it through, I like the landing page better. We couldn't really test people's localhost connections unless they're forwarding ports to us.

**Comment by gabebw** [comment]
#22, #23

**Comment by gabebw** [comment]
Closing because #23 is merged.
