### ISSUE TITLE
Save the original HTTP Referer in the DB so we can find where the link is

### ISSUE THREAD

**Issue by gabebw** [gabebw/hotline-webring#56]
We normalize the Referer before saving it to the DB. We should still use that normalized Referer, and also save the original raw Referer so we can find where the original HLWR links are.

**Comment by edwardloveall** [comment]
Alternative: We just use the full url as the redirection url

**Comment by gabebw** [comment]
I like that idea.

**Comment by edwardloveall** [comment]
I (again) remembered why we didn't do this:

If someone has the webring links as part of their website's global template, they could trigger a new redirection to be added.

Example: http://nuthole.com and http://nuthole.com/blog/2016/05/03/jack-shirt/ 

This gets into more of a discussion about if we want to maintain the way we add new redirections to the ring.

**Comment by gabebw** [comment]
This might be fixed by #58; let's see.

**Comment by gabebw** [comment]
This will be fixed by #115.

**Comment by gabebw** [comment]
#115 was merged, so I'm closing this issue.
