### ISSUE TITLE
URI Postgres "Datatype"

### ISSUE THREAD

**Issue by adarsh** [gabebw/hotline-webring#57]
We are [saving the URL as a text field](https://github.com/gabebw/hotline-webring/blob/6575d5c12e7825f18556892f302309b0f8642c76/db/schema.rb#L24), which makes total sense.

Postgres is usually pretty progressive about datatypes, so in my mind, one was `URI`. Turns out there is [plenty of network types](https://www.postgresql.org/docs/9.5/static/datatype-net-types.html) including `IPV4/6` and `MAC` but not `URI`.

Since [no one has been successfully bribed to write the datatype](https://twitter.com/pvh/status/567395527357001728), there is this extension:

https://github.com/petere/pguri

> This is an extension for PostgreSQL that provides a uri data type. Advantages over using plain text for storing URIs include:
> - URI syntax checking
> - functions for extracting URI components
> - human-friendly sorting

Caveats:

> Note that this might not be the right data type to use if you want to store user-provided URI data, such as HTTP referrers, since they might contain arbitrary junk.

This may not be helpful but I figured it was worth looking into for educational purposes.

**Comment by gabebw** [comment]
That's pretty neat! I think the benefits of a custom datatype are custom querying, like "Search for any IP addresses in a specific block". We are not really slicing and dicing the URL that much, though maybe we should start doing that...
