### ISSUE TITLE
YouTube embed is showing security warnings

### ISSUE THREAD

**Issue by edwardloveall** [gabebw/hotline-webring#62]
When loading the page this error is displayed in the console:

> XMLHttpRequest cannot load https://googleads.g.doubleclick.net/pagead/id. Origin https://www.youtube-nocookie.com is not allowed by Access-Control-Allow-Origin.

I believe this is because of our YouTube embed. It also displays a nasty warning on chrome:
![screen shot 2017-03-27 at 12 55 48 pm](https://cloud.githubusercontent.com/assets/49549/24368044/fabf4734-12ec-11e7-9b1e-04d893832de5.png)

**Comment by gabebw** [comment]
I think it's our [counter code](https://github.com/gabebw/hotline-webring/blob/402be933bea760df21498952464496befb79c9f8/app/views/homes/show.html.erb#L75-L80). We should just remove it.

**Comment by gabebw** [comment]
![hotline webring 2017-03-27 10-20-09](https://cloud.githubusercontent.com/assets/257678/24368856/f22351c6-12d6-11e7-9cb9-0fbaba39b4c8.png)

**Comment by gabebw** [comment]
This is a dupe of #53, I think.

**Comment by edwardloveall** [comment]
I think you're right about the warning dialog, but what about the doubleclick error?

**Comment by gabebw** [comment]
That's my adblock plugin blocking ad scripts like Doubleclick.

**Comment by edwardloveall** [comment]
No adblock on the computer i'm testing on

**Comment by gabebw** [comment]
Oooh, I thought you were pointing out the second line of my screenshot, which references doubleclick.

I think that there are two things happening here:

1. "This page is trying to load scripts from unsafe sources" is, I think, an error from our http-not-https counter script. 
2. The Doubleclick/Access-Control-Allow-Origin problem is from Youtube, but....I sort of don't care? Like, not loading Doubleclick ad code feels like a feature to me, not a bug, even if it does show a console error. We _could_ add `Access-Control-Allow-Origin` headers that disallow doubleclick, which would probably get rid of the error.

**Comment by edwardloveall** [comment]
Hmm okay. I'm included to also not care. Close?

**Comment by gabebw** [comment]
Agreed, closing.
