### ISSUE TITLE
Get a domain name

### ISSUE THREAD

**Issue by adarsh** [gabebw/hotline-webring#7]
Some options:

My favorite is `hotlinewebring.club`

![image](https://cloud.githubusercontent.com/assets/913757/11344669/8bba4458-91c7-11e5-948e-a2cd42ff7ff7.png)

![image](https://cloud.githubusercontent.com/assets/913757/11344715/bb259a44-91c7-11e5-8d02-b99f839c90f7.png)

**Comment by gabebw** [comment]
I actually already bought webring.online!

**Comment by gabebw** [comment]
OK I just bought hotlinewebring.club too, wheeee
